language: android
android:
  components:
  - build-tools-28.0.3
  - android-23
jdk:
- openjdk8

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1

script:
- "./gradlew test"
- "./gradlew desktop:distZip"
- "./gradlew android:assembleRelease"